# Generated by Django 3.1 on 2020-09-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_of_birth',
        ),
    ]
