# Generated by Django 3.1.1 on 2020-09-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0008_operatordocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='no_of_days',
            field=models.IntegerField(),
        ),
    ]
