# Generated by Django 3.1.1 on 2020-09-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0010_messagequries'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagequries',
            name='sender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
