# Generated by Django 3.1.1 on 2020-09-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0012_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
