# Generated by Django 3.1.1 on 2020-09-30 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0013_invoices_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='notes',
        ),
    ]
