# Generated by Django 3.1.1 on 2020-10-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0015_auto_20201006_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='read_by_client',
            field=models.BooleanField(default=False),
        ),
    ]
