# Generated by Django 3.1.1 on 2020-10-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0016_invoices_read_by_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='read_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='read_by_operator',
            field=models.BooleanField(default=False),
        ),
    ]
