# Generated by Django 3.1.1 on 2020-10-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0017_auto_20201006_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='read_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='read_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='read_by_operator',
            field=models.BooleanField(default=False),
        ),
    ]
