# Generated by Django 3.1.1 on 2020-10-09 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientApp', '0018_auto_20201006_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empyloyee',
            fields=[
                ('employee_user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_designation', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('total_leaves', models.IntegerField()),
                ('available_leaves', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employee_profile_picture')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
