# Generated by Django 3.1.1 on 2020-10-11 15:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0020_auto_20201009_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocuments',
            fields=[
                ('doc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_title', models.CharField(max_length=100)),
                ('documents', models.FileField(upload_to='employee_documents')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientApp.operator')),
            ],
        ),
    ]
