# Generated by Django 3.1.1 on 2020-10-11 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0021_employeedocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocuments',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientApp.employee'),
        ),
    ]
