# Generated by Django 3.1.1 on 2020-10-11 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientApp', '0023_employeeholiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFeedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.CharField(choices=[('', 'Choose...'), ('One Star', 'One Star'), ('Two Star', 'Two Star'), ('Three Star', 'Three Star'), ('Four Star', 'Four Star'), ('Five Star', 'Five Star')], max_length=20)),
                ('feedback_note', models.TextField()),
                ('read_by_employee', models.BooleanField(default=False)),
                ('admin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientApp.employee')),
            ],
        ),
    ]
