# Generated by Django 3.1.1 on 2020-10-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0024_employeefeedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeDocuments',
            new_name='EmployeeDocument',
        ),
    ]
