# Generated by Django 3.1.1 on 2020-10-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0025_auto_20201019_1839'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoices',
            new_name='Invoice',
        ),
    ]
