# Generated by Django 3.1.1 on 2020-10-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0026_auto_20201019_1845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OperatorDocuments',
            new_name='OperatorDocument',
        ),
    ]
