from django.urls import path
from django.contrib.auth.models import User

from . import views
from secondProject.views import ClientRegistration, OperatorRegistration

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('signup-operator/', OperatorRegistration.as_view(), name='operator_signup'),
    path('signup/', ClientRegistration.as_view(), name='client_signup'),
    path('admin-signup/', ClientRegistration.as_view(),
         name='admin_client_signup'),
    path('profile/<slug:pk>/', views.ClientProfileView.as_view(),
         name='client_profile'),
    path('operator/profile/<slug:pk>/',
         views.OperatorProfileView.as_view(), name='operator_profile'),
    path('feedback/', views.FeedbackView.as_view(), name='client_feedback'),
    path('feedback/list/', views.ListClientFeedbackView.as_view(),
         name='client_feedback_list'),
    path('feedback/operator/list/', views.ListOperatorFeedbackView.as_view(),
         name='operator_feedback_list'),
    path('feedback/admin/list/', views.ListAdminFeedbackView.as_view(),
         name='admin_feedback_list'),
    path('operator/leave-request', views.OperatorLeaveRequest.as_view(),
         name='operator_leave_request'),
    path('operator/leave-request/list/<str:action>',
         views.OperatorLeaveList.as_view(), name='operator_leave_list'),
    path('operator/leave-request/detail/<slug:pk>',
         views.OperatorLeaveDetail.as_view(), name='operator_leave_detail'),
    path('leave-request/list/<str:action>',
         views.ClientLeaveList.as_view(), name='leave_list'),
    path('leave-request/approve/<slug:pk>',
         views.leave_approve, name='leave_approve'),
    path('leave-request/reject/<slug:pk>',
         views.leave_reject, name='leave_reject'),
    path('leave-request/admin/list/<str:action>',
         views.AdminLeaveList.as_view(), name='admin_leave_list'),
    path('operator/documents/upload', views.OperatorDocumentsUpload.as_view(),
         name='operator_document_upload'),
    path('operator/documents/list', views.OperatorDocumentsList.as_view(),
         name='operator_document_list'),
    path('operator/documents/delete/<slug:pk>',
         views.operatorDocumetDelete, name='operator_document_delete'),
    path('operator/list', views.ClientOperatorList.as_view(),
         name='client_operator_list'),
    path('operator/documents/<slug:pk>',
         views.ClientOperatorDocumentsList.as_view(), name='client_operator_documents'),
    path('invoices/upload', views.ClientInvoiceUpload.as_view(),
         name='admin_invoice_upload'),
    path('invoices/admin/list', views.AdminInvoiceList.as_view(),
         name='admin_invoice_list'),
    path('invoices/admin/delete/<slug:pk>',
         views.invoiceDelete, name='admin_invoice_delete'),
    path('invoice/list', views.ClientInvoiceList.as_view(),
         name='client_invoice_list'),
    path('operator/message/list', views.OperatorViewMessages.as_view(),
         name='operator_message_list'),
    path('message/client/operator/<slug:pk>',
         views.ClientOperatorViewMessage.as_view(), name='client_message_operator_list'),
    path('message/admin/<int:pk>', views.ClientAdminViewMessage.as_view(),
         name='client_admin_message_list'),
    path('message/client/<slug:pk>', views.AdminClientViewMessage.as_view(),
         name='admin_client_message_list'),
    path('message/admin/operator/<slug:pk>',
         views.AdminOperatorViewMessage.as_view(), name='admin_operator_message_list'),
]

app_name = 'clientApp'
