# Generated by Django 3.1 on 2020-09-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0002_remove_client_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operator',
            old_name='avaliable_leaves',
            new_name='available_leaves',
        ),
        migrations.AddField(
            model_name='client',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
