# Generated by Django 3.1 on 2020-09-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0003_auto_20200903_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='is_client',
        ),
    ]
