# Generated by Django 3.1 on 2020-09-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0004_auto_20200903_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='admin_leave_status',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='leave',
            name='client_leave_status',
            field=models.BooleanField(default=False),
        ),
    ]
