# Generated by Django 3.1 on 2020-09-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0005_auto_20200909_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
