# Generated by Django 3.1 on 2020-09-17 18:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0007_auto_20200916_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorDocuments',
            fields=[
                ('doc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_title', models.CharField(max_length=100)),
                ('documents', models.FileField(upload_to='operator_documents')),
                ('operator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientApp.operator')),
            ],
        ),
    ]
